### ISSUE TITLE
Tracking Power Use and Temperature

### ISSUE THREAD

**Issue by aabbi** [congard/nvidia-system-monitor-qt#12]
Nvidia smi usually displays this information in its output by default. Would it be useful to include this information as well ?

If so, willing to work on adding it but would like to know if you have an opinion on which tab it should go on and should it be displayed as a graph or point in time ?

**Comment by congard** [comment]
Hi, I think we can't add this now because the app really needs the Graph class and a lot of refactoring. Will try to do it tomorrow. But I haven't any idea of how it should be. I think that merging 2nd and 3rd tabs good idea, isn't it? Like Windows or gnome/kde system monitors. Then we can easily add power use and temperature. Also, I think that it should be 1 gpu per graph, not all gpus in one graph. If you like some of these ideas, let me know

**Comment by aabbi** [comment]
Yes, merging the tabs would definitely be better as it both lets you compare and you don't need to switch tabs. 

About multiple gpus - I haven't really used them so wouldn't be able to say if it is useful to compare the same metrics across multiple gpus or not. 

I'll close this for now
